web/router.ex
defmodule Debate.Router do
  use Debate.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Debate do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/random", RandomController, :index
    post "/results", RandomController, :random
  end

  # Other scopes may use custom stacks.
  # scope "/api", Debate do
  #   pipe_through :api
  # end
end

lib/debate/endpoint.ex
defmodule Debate.Endpoint do
  use Phoenix.Endpoint, otp_app: :debate

  socket "/socket", Debate.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :debate, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_debate_key",
    signing_salt: "sN5Y56q+"

  plug Debate.Router
end

lib/debate/repo.ex
defmodule Debate.Repo do
  use Ecto.Repo, otp_app: :debate
end

web/models/random.ex
defmodule Debate.Random do
  use Debate.Web, :model

  schema "users" do
    field :grupo1, :string, virtual: true
    field :grupo2, :string, virtual: true
    field :grupo3, :string, virtual: true
    field :grupo4, :string, virtual: true
  end

  @required_fields ~w(grupo1 grupo2 grupo3 grupo4)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.
  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/controllers/page_controller.ex
defmodule Debate.PageController do
  use Debate.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/random_controller.ex
defmodule Debate.RandomController do
  use Debate.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def random(conn, %{"session" => session_params}) do
  	list = [session_params["grupo1"], session_params["grupo2"], session_params["grupo3"], session_params["grupo4"]]
    :random.seed(:erlang.now)
    newlist = Enum.take_random(list, 4)
    IO.puts newlist
    render(conn, "random.html", newlist: newlist)
  end
end

web/views/error_view.ex
defmodule Debate.ErrorView do
  use Debate.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Debate.LayoutView do
  use Debate.Web, :view
end

web/views/page_view.ex
defmodule Debate.PageView do
  use Debate.Web, :view
end

web/views/random_view.ex
defmodule Debate.RandomView do
  use Debate.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Debate!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/random/index.html.eex
<h2>Random</h2>

<%= form_for @conn, random_path(@conn, :random), [name: :session], fn f -> %>
  <div class="form-group">
    <label>Grupo1</label>
    <%= text_input f, :grupo1, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Grupo2</label>
    <%= text_input f, :grupo2, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Grupo3</label>
    <%= text_input f, :grupo3, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Grupo4</label>
    <%= text_input f, :grupo4, class: "form-control" %>
  </div>


  <div class="form-group">
    <%= submit "Sortear", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/random/random.html.eex
<h2>Result Random</h2>

<table class="table">
  <thead>
    <tr>
      <th>1er Gobierno</th>
      <th>1era Oposicion</th>
      <th>2do Gobierno</th>
      <th>2da Oposicion</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <%= for grupo <- @newlist do %>
      <td><%= grupo %></td>
    <% end %>
    </tr>
  </tbody>
</table>